"""
Django settings for django_template project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from django_template.settings.app_vars import *
from django_template.settings.apps import *
from django_template.settings.base import *
from django_template.settings.celery import *
from django_template.settings.database import *
from django_template.settings.logger import *
from django_template.settings.third_party import *
